[package]
name = "wgpu_dyn_buffer"
version = "3.0.0"
edition = "2021"
description = "Wgpu Dynamic Buffer"
license = "BSD-3-Clause"
repository = "https://github.com/CalebCouch/wgpu_dyn_buffer.git"

[dependencies]
wgpu = "25.0.0"
